#!/bin/bash
cd `dirname $(realpath $0)`

source ../confparams.sh
source ../commonfun.sh

result=0
echo
echo -e "${FFS_YEL}############################################${FFS_NOC}"
echo -e "${FFS_YEL} Cleaning the result of make bins procedure ${FFS_NOC}"
echo -e "${FFS_BLU} Script :${FFS_NOC}" "$0"
echo -e "${FFS_YEL}############################################${FFS_NOC}"
echo "GOPATH         = "$GOPATH
echo "FFS_FABRIC_BIN = "$FFS_FABRIC_BIN

_rmi
# rm $GOPATH only if it is defined in current dir. We need to be careful when removing $GOPATH ;)
DTR=`echo $GOPATH | sed "s!$PWD!.!g"`
test -d $DTR &&            bash -c "echo Removing dir $DTR located in $PWD; rm -rf $DTR" 

test -d $FFS_FABRIC_BIN && bash -c "echo Removing $FFS_FABRIC_BIN; rm -rf $FFS_FABRIC_BIN"

if [[ .$result. == .0. ]]; then
        echo -e "Script result: ${FFS_GRE}SUCCESS${FFS_NOC}"
else
        echo -e "Script result: ${FFS_RED}FAILED${FFS_NOC}"
fi

exit $result
