#!/bin/bash
cd `dirname $(realpath $0)`

source ../confparams.sh
result=0
./s01.installcc; (( result = result + $? ))
./s02.instantiatecc; (( result = result + $? ))
./s03.querycc; (( result = result + $? ))
./s04.invokecc; (( result = result + $? ))
sleep 5
./s05.checkquerycc; (( result = result + $? ))

if [[ .$result. == .0. ]]; then
        echo -e "Section result: ${FFS_GRE}SUCCESS${FFS_NOC}"
	exit 0
else
        echo -e "Section result: ${FFS_RED}FAILED${FFS_NOC}"
	exit 1
fi
