#!/bin/bash
cd `dirname $(realpath $0)`
source ../confparams.sh

result=0
./s01.mkcrypto; (( result = result + $? ))
./s02.cppubcerts; (( result = result + $? ))

if [[ .$result. == .0. ]]; then
        echo -e "Section result: ${FFS_GRE}SUCCESS${FFS_NOC}"
	exit 0
else
        echo -e "Section result: ${FFS_RED}FAILED${FFS_NOC}"
	exit 1
fi
